// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;

class Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(io_master_awready,0,0);
        VL_OUT8(io_master_awvalid,0,0);
        VL_OUT8(io_master_awid,3,0);
        VL_OUT8(io_master_awlen,7,0);
        VL_OUT8(io_master_awsize,2,0);
        VL_OUT8(io_master_awburst,1,0);
        VL_IN8(io_master_wready,0,0);
        VL_OUT8(io_master_wvalid,0,0);
        VL_OUT8(io_master_wstrb,3,0);
        VL_OUT8(io_master_wlast,0,0);
        VL_OUT8(io_master_bready,0,0);
        VL_IN8(io_master_bvalid,0,0);
        VL_IN8(io_master_bresp,1,0);
        VL_IN8(io_master_bid,3,0);
        VL_IN8(io_master_arready,0,0);
        VL_OUT8(io_master_arvalid,0,0);
        VL_OUT8(io_master_arid,3,0);
        VL_OUT8(io_master_arlen,7,0);
        VL_OUT8(io_master_arsize,2,0);
        VL_OUT8(io_master_arburst,1,0);
        VL_OUT8(io_master_rready,0,0);
        VL_IN8(io_master_rvalid,0,0);
        VL_IN8(io_master_rresp,1,0);
        VL_IN8(io_master_rlast,0,0);
        VL_IN8(io_master_rid,3,0);
        CData/*0:0*/ top__DOT__bpu_pc_valid_o;
        CData/*0:0*/ top__DOT__pdt_res;
        CData/*0:0*/ top__DOT__which_pdt_o;
        CData/*0:0*/ top__DOT__pdt_correct;
        CData/*0:0*/ top__DOT__id_ras_push_valid;
        CData/*0:0*/ top__DOT__csr_imm_valid_o;
        CData/*0:0*/ top__DOT__mem_addr_valid;
        CData/*3:0*/ top__DOT__mem_mask;
        CData/*0:0*/ top__DOT__mem_write_valid;
        CData/*0:0*/ top__DOT__mem_data_ready;
        CData/*0:0*/ top__DOT__csr_write_valid_mem;
        CData/*4:0*/ top__DOT__rd_addr_mem_wb;
        CData/*0:0*/ top__DOT__clint_csr_write_en;
        CData/*1:0*/ top__DOT__next_privilege;
        CData/*0:0*/ top__DOT__ram_rdata_ready_dcache;
        CData/*5:0*/ top__DOT__ifu__DOT__bpu__DOT__ras_sp;
        CData/*5:0*/ top__DOT__ifu__DOT__bpu__DOT__pred_ras_sp;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__pred_used_ras;
        CData/*1:0*/ top__DOT__ifu__DOT__bpu__DOT__provider_history_reg;
        CData/*1:0*/ top__DOT__ifu__DOT__bpu__DOT__provider_history_comb;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__ras_forward_valid;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__ras_forward_used;
        CData/*5:0*/ top__DOT__ifu__DOT__bpu__DOT__next_sp;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__pop_occurred;
        CData/*5:0*/ top__DOT__ifu__DOT__bpu__DOT__pop_index;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__btb_hit;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__is_ret;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__ex_is_ret;
        CData/*7:0*/ top__DOT__ifu__DOT__bpu__DOT__t0_index;
        CData/*7:0*/ top__DOT__ifu__DOT__bpu__DOT__t1_index;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__t0_match;
        CData/*0:0*/ top__DOT__ifu__DOT__bpu__DOT__t1_match;
        CData/*5:0*/ top__DOT__ifu__DOT__bpu__DOT__ex_next_ras_sp;
        CData/*7:0*/ top__DOT__ifu__DOT__bpu__DOT__t0_index_u;
        CData/*7:0*/ top__DOT__ifu__DOT__bpu__DOT__t1_index_u;
        CData/*7:0*/ top__DOT__ifu__DOT__bpu__DOT__btb_index_u;
        CData/*0:0*/ top__DOT__if2id__DOT__reg_rst;
    };
    struct {
        CData/*0:0*/ top__DOT__if2id__DOT___bpu_taken_if_id_q;
        CData/*0:0*/ top__DOT__if2id__DOT___bpu_pdt_res_if_id_q;
        CData/*0:0*/ top__DOT__if2id__DOT___bpu_which_pdt_if_id_q;
        CData/*0:0*/ top__DOT__idu__DOT___inst_lui;
        CData/*0:0*/ top__DOT__idu__DOT___inst_auipc;
        CData/*0:0*/ top__DOT__idu__DOT___inst_jal;
        CData/*0:0*/ top__DOT__idu__DOT___inst_jalr;
        CData/*0:0*/ top__DOT__idu__DOT___inst_beq;
        CData/*0:0*/ top__DOT__idu__DOT___inst_bne;
        CData/*0:0*/ top__DOT__idu__DOT___inst_blt;
        CData/*0:0*/ top__DOT__idu__DOT___inst_bge;
        CData/*0:0*/ top__DOT__idu__DOT___inst_bltu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_bgeu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_lb;
        CData/*0:0*/ top__DOT__idu__DOT___inst_lh;
        CData/*0:0*/ top__DOT__idu__DOT___inst_lw;
        CData/*0:0*/ top__DOT__idu__DOT___inst_lbu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_lhu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sb;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sh;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sw;
        CData/*0:0*/ top__DOT__idu__DOT___inst_addi;
        CData/*0:0*/ top__DOT__idu__DOT___inst_slti;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sltiu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_xori;
        CData/*0:0*/ top__DOT__idu__DOT___inst_ori;
        CData/*0:0*/ top__DOT__idu__DOT___inst_andi;
        CData/*0:0*/ top__DOT__idu__DOT___inst_slli;
        CData/*0:0*/ top__DOT__idu__DOT___inst_srli;
        CData/*0:0*/ top__DOT__idu__DOT___inst_srai;
        CData/*0:0*/ top__DOT__idu__DOT___inst_add;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sub;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sll;
        CData/*0:0*/ top__DOT__idu__DOT___inst_slt;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sltu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_xor;
        CData/*0:0*/ top__DOT__idu__DOT___inst_srl;
        CData/*0:0*/ top__DOT__idu__DOT___inst_sra;
        CData/*0:0*/ top__DOT__idu__DOT___inst_or;
        CData/*0:0*/ top__DOT__idu__DOT___inst_and;
        CData/*0:0*/ top__DOT__idu__DOT___inst_ecall;
        CData/*0:0*/ top__DOT__idu__DOT___inst_ebreak;
        CData/*0:0*/ top__DOT__idu__DOT___inst_mret;
        CData/*0:0*/ top__DOT__idu__DOT___inst_csrrw;
        CData/*0:0*/ top__DOT__idu__DOT___inst_csrrs;
        CData/*0:0*/ top__DOT__idu__DOT___inst_csrrc;
        CData/*0:0*/ top__DOT__idu__DOT___inst_csrrwi;
        CData/*0:0*/ top__DOT__idu__DOT___inst_csrrsi;
        CData/*0:0*/ top__DOT__idu__DOT___inst_csrrci;
        CData/*0:0*/ top__DOT__idu__DOT___inst_mul;
        CData/*0:0*/ top__DOT__idu__DOT___inst_mulh;
        CData/*0:0*/ top__DOT__idu__DOT___inst_mulhsu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_mulhu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_div;
        CData/*0:0*/ top__DOT__idu__DOT___inst_divu;
        CData/*0:0*/ top__DOT__idu__DOT___inst_rem;
        CData/*0:0*/ top__DOT__idu__DOT___inst_remu;
        CData/*0:0*/ top__DOT__idu__DOT___type_branch;
        CData/*0:0*/ top__DOT__idu__DOT___type_load;
        CData/*0:0*/ top__DOT__idu__DOT___type_store;
        CData/*0:0*/ top__DOT__idu__DOT___type_Imm_add;
        CData/*0:0*/ top__DOT__idu__DOT___type_Reg;
        CData/*0:0*/ top__DOT__idu__DOT___I_type;
        CData/*0:0*/ top__DOT__idu__DOT___U_type;
    };
    struct {
        CData/*0:0*/ top__DOT__idu__DOT___isNeed_csr;
        CData/*0:0*/ top__DOT__idu__DOT___rs1_exc_bypass_valid;
        CData/*0:0*/ top__DOT__idu__DOT___rs2_exc_bypass_valid;
        CData/*0:0*/ top__DOT__idu__DOT___csr_write;
        CData/*0:0*/ top__DOT__idu__DOT___csr_set;
        CData/*0:0*/ top__DOT__idu__DOT___csr_clear;
        CData/*0:0*/ top__DOT__idu__DOT___csr_read;
        CData/*0:0*/ top__DOT__idu__DOT____Vlvbound_heef95465__0;
        CData/*0:0*/ top__DOT__idu__DOT____Vlvbound_heef95465__1;
        CData/*0:0*/ top__DOT__idu__DOT____Vlvbound_heef95465__2;
        CData/*0:0*/ top__DOT__idu__DOT____Vlvbound_heef95465__3;
        CData/*0:0*/ top__DOT__idu__DOT____Vlvbound_heef95465__4;
        CData/*0:0*/ top__DOT__idu__DOT____VdfgTmp_h7e5e33d0__0;
        CData/*0:0*/ top__DOT__idu__DOT____VdfgTmp_h2ad227db__0;
        CData/*0:0*/ top__DOT__id2ex__DOT__reg_rst;
        CData/*0:0*/ top__DOT__id2ex__DOT___bpu_taken_id_ex_q;
        CData/*0:0*/ top__DOT__id2ex__DOT___bpu_pdt_res_id_ex_q;
        CData/*0:0*/ top__DOT__id2ex__DOT___bpu_which_pdt_id_ex_q;
        CData/*4:0*/ top__DOT__id2ex__DOT___rs1_idx_id_ex_d;
        CData/*4:0*/ top__DOT__id2ex__DOT___rs1_idx_id_ex_q;
        CData/*4:0*/ top__DOT__id2ex__DOT___rs2_idx_id_ex_d;
        CData/*4:0*/ top__DOT__id2ex__DOT___rs2_idx_id_ex_q;
        CData/*4:0*/ top__DOT__id2ex__DOT___rd_idx_id_ex_q;
        CData/*0:0*/ top__DOT__id2ex__DOT___csr_imm_valid_id_ex_d;
        CData/*0:0*/ top__DOT__id2ex__DOT___csr_imm_valid_id_ex_q;
        CData/*4:0*/ top__DOT__id2ex__DOT___csr_op_id_ex_q;
        CData/*3:0*/ top__DOT__id2ex__DOT___mem_op_id_ex_q;
        CData/*3:0*/ top__DOT__id2ex__DOT___pc_op_id_ex_q;
        CData/*0:0*/ top__DOT__exu__DOT__is_branch_inst;
        CData/*0:0*/ top__DOT__exu__DOT__jump_taken;
        CData/*0:0*/ top__DOT__exu__DOT__bpu_pc_wrong;
        CData/*0:0*/ top__DOT__exu__DOT___rs1_rs2;
        CData/*0:0*/ top__DOT__exu__DOT___rs1_imm;
        CData/*0:0*/ top__DOT__exu__DOT___pc_4;
        CData/*0:0*/ top__DOT__exu__DOT___compare_out;
        CData/*0:0*/ top__DOT__exu__DOT____Vlvbound_h78faab82__0;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT___isCMP;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT___isSUBop;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT___isCF;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT___isSLT;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT___is_mul_sr1_signed;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT___is_mul_sr2_signed;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__mul_stall_req;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT___is_div_signed;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__div_stall_req;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT____VdfgTmp_h310dda4a__0;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT____VdfgTmp_h374b09af__0;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_shift__DOT____VdfgTmp_h17d4dcd5__0;
        CData/*2:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__mul_state;
        CData/*3:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__mul_count;
        CData/*3:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__mul_count_plus1;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__mul_ready;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__booth_rs1_signed_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__booth_rs2_signed_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__1__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__1__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__2__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__2__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__3__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__3__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__4__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__4__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__5__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__5__KET____DOT__x_neg_valid;
    };
    struct {
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__6__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__6__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__7__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__7__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__8__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__8__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__9__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__9__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__10__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__10__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__11__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__11__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__12__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__12__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__13__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__13__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__14__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__14__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__15__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__15__KET____DOT__x_neg_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__16__KET____DOT__x_valid;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__gen_pp__BRA__16__KET____DOT__x_neg_valid;
        CData/*2:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div_state;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div_ready;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div32_rs1_sign;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__add_d_32;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__need_coreect_32;
        CData/*0:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div_count_is_zero;
        CData/*0:0*/ top__DOT__ex2mem__DOT__reg_rst;
        CData/*4:0*/ top__DOT__ex2mem__DOT___rd_idx_ex_mem_q;
        CData/*0:0*/ top__DOT__ex2mem__DOT___csr_writevalid_ex_mem_q;
        CData/*3:0*/ top__DOT__ex2mem__DOT___pc_op_ex_mem_q;
        CData/*3:0*/ top__DOT__ex2mem__DOT___mem_op_ex_mem_q;
        CData/*0:0*/ top__DOT__lsu__DOT___isload;
        CData/*0:0*/ top__DOT__lsu__DOT___ls8byte;
        CData/*0:0*/ top__DOT__lsu__DOT___ls16byte;
        CData/*0:0*/ top__DOT__lsu__DOT___ls32byte;
        CData/*0:0*/ top__DOT__lsu__DOT__ls_signed;
        CData/*3:0*/ top__DOT__lsu__DOT__ls_size;
        CData/*3:0*/ top__DOT__lsu__DOT___mask;
        CData/*1:0*/ top__DOT__lsu__DOT__addr_last2;
        CData/*0:0*/ top__DOT__lsu__DOT____Vlvbound_hda221a3d__0;
        CData/*0:0*/ top__DOT__lsu__DOT____VdfgTmp_h7035a01d__0;
        CData/*0:0*/ top__DOT__clint_u__DOT__trap_valid;
        CData/*0:0*/ top__DOT__clint_u__DOT__machine_timer_interrupt;
        CData/*0:0*/ top__DOT__clint_u__DOT__supervisor_timer_interrupt;
        CData/*0:0*/ top__DOT__clint_u__DOT__mtime_ge_mtime;
        CData/*0:0*/ top__DOT__clint_u__DOT__interrupt_pending;
        CData/*4:0*/ top__DOT__clint_u__DOT__interrupt_code;
        CData/*0:0*/ top__DOT__clint_u__DOT__interrupt_delegated;
        CData/*0:0*/ top__DOT__clint_u__DOT__is_delegated_latched;
        CData/*0:0*/ top__DOT__clint_u__DOT__interrupt_pending_latched;
        CData/*2:0*/ top__DOT__clint_u__DOT__csr_state;
        CData/*2:0*/ top__DOT__clint_u__DOT__next_csr_state;
        CData/*0:0*/ top__DOT__clint_u__DOT__is_delegated;
        CData/*0:0*/ top__DOT__clint_u__DOT__mtime_write_valid_i;
        CData/*5:0*/ top__DOT__clint_u__DOT__u_pipline_control__DOT___flush;
        CData/*5:0*/ top__DOT__clint_u__DOT__u_pipline_control__DOT___stall;
        CData/*1:0*/ top__DOT__rv32_csr_regfile__DOT__privilegeReg;
        CData/*0:0*/ top__DOT__rv32_csr_regfile__DOT__read_error;
        CData/*0:0*/ top__DOT__rv32_gpr_regfile__DOT___rs1_bypass_valid;
        CData/*0:0*/ top__DOT__rv32_gpr_regfile__DOT___rs2_bypass_valid;
        CData/*0:0*/ top__DOT__u_icache_top__DOT__icache_hit;
        CData/*3:0*/ top__DOT__u_icache_top__DOT__icache_state;
    };
    struct {
        CData/*5:0*/ top__DOT__u_icache_top__DOT__blk_addr_reg;
        CData/*6:0*/ top__DOT__u_icache_top__DOT__line_idx_reg;
        CData/*0:0*/ top__DOT__u_icache_top__DOT__icache_tag_write_valid;
        CData/*0:0*/ top__DOT__u_icache_top__DOT__uncache_data_ready;
        CData/*0:0*/ top__DOT__u_icache_top__DOT___ram_raddr_valid_icache_o;
        CData/*3:0*/ top__DOT__u_icache_top__DOT___ram_rmask_icache_o;
        CData/*3:0*/ top__DOT__u_icache_top__DOT___ram_rsize_icache_o;
        CData/*7:0*/ top__DOT__u_icache_top__DOT___ram_rlen_icache_o;
        CData/*3:0*/ top__DOT__u_icache_top__DOT__burst_count;
        CData/*0:0*/ top__DOT__u_icache_top__DOT__ram_r_handshake;
        CData/*3:0*/ top__DOT__u_icache_top__DOT__burst_count_plus1;
        CData/*3:0*/ top__DOT__u_dcache_top__DOT__dcache_state;
        CData/*5:0*/ top__DOT__u_dcache_top__DOT__blk_addr_reg;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__dcache_tag_wen;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__dcache_data_ready;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT___ram_raddr_valid_dcache_o;
        CData/*3:0*/ top__DOT__u_dcache_top__DOT___ram_rmask_dcache_o;
        CData/*3:0*/ top__DOT__u_dcache_top__DOT___ram_rsize_dcache_o;
        CData/*7:0*/ top__DOT__u_dcache_top__DOT___ram_rlen_dcache_o;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT___ram_waddr_valid_dcache_o;
        CData/*3:0*/ top__DOT__u_dcache_top__DOT___ram_wmask_dcache_o;
        CData/*3:0*/ top__DOT__u_dcache_top__DOT___ram_wsize_dcache_o;
        CData/*7:0*/ top__DOT__u_dcache_top__DOT___ram_wlen_dcache_o;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__dcache_data_wen;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT___dirty_bit_write;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__dcache_write_hit_valid;
        CData/*3:0*/ top__DOT__u_dcache_top__DOT__burst_count;
        CData/*3:0*/ top__DOT__u_dcache_top__DOT__burst_count_plus1;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT___dirty_flush;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__ram_r_handshake;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__ram_w_handshake;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__dcache_wwen;
        CData/*6:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT__A;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT__hit_CEN00;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT__hit_CEN01;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT__hit_CEN10;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT__hit_CEN11;
        CData/*1:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT____VdfgTmp_h5837c3bf__0;
        CData/*0:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT____VdfgTmp_h5eeedcde__0;
        CData/*0:0*/ top__DOT__axi_arb__DOT___arb_raddr_valid_o;
        CData/*3:0*/ top__DOT__axi_arb__DOT___arb_rmask_o;
        CData/*3:0*/ top__DOT__axi_arb__DOT___arb_rsize_o;
        CData/*7:0*/ top__DOT__axi_arb__DOT___arb_rlen_o;
        CData/*1:0*/ top__DOT__axi_arb__DOT__arb_state;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__axi_ar_handshake;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__axi_aw_handshake;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__axi_r_handshake;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__axi_w_handshake;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__axi_b_handshake;
        CData/*2:0*/ top__DOT__axi4_rw__DOT__to_aw_size;
        CData/*2:0*/ top__DOT__axi4_rw__DOT__axi_wstate;
        CData/*0:0*/ top__DOT__axi4_rw__DOT___arb_wdata_ready_o;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__aw_valid;
        CData/*7:0*/ top__DOT__axi4_rw__DOT__aw_len;
        CData/*2:0*/ top__DOT__axi4_rw__DOT__aw_size;
        CData/*3:0*/ top__DOT__axi4_rw__DOT__w_strb;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__w_valid;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__w_last;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__b_ready;
        CData/*7:0*/ top__DOT__axi4_rw__DOT__burst_count;
        CData/*7:0*/ top__DOT__axi4_rw__DOT__burst_count_plus1;
        CData/*2:0*/ top__DOT__axi4_rw__DOT__axi_rstate;
        CData/*0:0*/ top__DOT__axi4_rw__DOT___arb_rdata_ready_o;
        CData/*0:0*/ top__DOT__axi4_rw__DOT___arb_rlast_o;
    };
    struct {
        CData/*0:0*/ top__DOT__axi4_rw__DOT__ar_valid;
        CData/*2:0*/ top__DOT__axi4_rw__DOT__ar_size;
        CData/*7:0*/ top__DOT__axi4_rw__DOT__ar_len;
        CData/*0:0*/ top__DOT__axi4_rw__DOT__r_ready;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM0__DOT__wen;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM1__DOT__wen;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM2__DOT__wen;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM3__DOT__wen;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM4__DOT__wen;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM5__DOT__wen;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM6__DOT__wen;
        CData/*0:0*/ top__DOT__sram__DOT__SRAM7__DOT__wen;
        CData/*0:0*/ __Vfunc_match__2__Vfuncout;
        CData/*0:0*/ __Vfunc_match__3__Vfuncout;
        CData/*0:0*/ __Vfunc_match__4__Vfuncout;
        CData/*0:0*/ __Vfunc_match__5__Vfuncout;
        CData/*0:0*/ __Vfunc_match__6__Vfuncout;
        CData/*0:0*/ __Vfunc_match__7__Vfuncout;
        CData/*0:0*/ __Vfunc_match__8__Vfuncout;
        CData/*0:0*/ __Vfunc_match__9__Vfuncout;
        CData/*0:0*/ __Vfunc_match__10__Vfuncout;
        CData/*0:0*/ __Vfunc_match__11__Vfuncout;
        CData/*0:0*/ __Vfunc_match__12__Vfuncout;
        CData/*0:0*/ __Vfunc_match__13__Vfuncout;
        CData/*0:0*/ __Vfunc_match__14__Vfuncout;
        CData/*0:0*/ __Vfunc_match__15__Vfuncout;
        CData/*0:0*/ __Vfunc_match__16__Vfuncout;
        CData/*0:0*/ __Vfunc_match__17__Vfuncout;
        CData/*0:0*/ __Vfunc_match__18__Vfuncout;
        CData/*0:0*/ __Vfunc_match__19__Vfuncout;
        CData/*0:0*/ __Vfunc_match__20__Vfuncout;
        CData/*0:0*/ __Vfunc_match__21__Vfuncout;
        CData/*0:0*/ __Vfunc_match__22__Vfuncout;
        CData/*0:0*/ __Vfunc_match__23__Vfuncout;
        CData/*0:0*/ __Vfunc_match__24__Vfuncout;
        CData/*0:0*/ __Vfunc_match__25__Vfuncout;
        CData/*0:0*/ __Vfunc_match__26__Vfuncout;
        CData/*0:0*/ __Vfunc_match__27__Vfuncout;
        CData/*0:0*/ __Vfunc_match__28__Vfuncout;
        CData/*0:0*/ __Vfunc_match__29__Vfuncout;
        CData/*0:0*/ __Vfunc_match__30__Vfuncout;
        CData/*0:0*/ __Vfunc_match__31__Vfuncout;
        CData/*0:0*/ __Vfunc_match__32__Vfuncout;
        CData/*0:0*/ __Vfunc_match__33__Vfuncout;
        CData/*0:0*/ __Vfunc_match__34__Vfuncout;
        CData/*0:0*/ __Vfunc_match__35__Vfuncout;
        CData/*0:0*/ __Vfunc_match__36__Vfuncout;
        CData/*0:0*/ __Vfunc_match__37__Vfuncout;
        CData/*0:0*/ __Vfunc_match__38__Vfuncout;
        CData/*0:0*/ __Vfunc_match__39__Vfuncout;
        CData/*0:0*/ __Vfunc_match__40__Vfuncout;
        CData/*0:0*/ __Vfunc_match__41__Vfuncout;
        CData/*0:0*/ __Vfunc_match__42__Vfuncout;
        CData/*0:0*/ __Vfunc_match__43__Vfuncout;
        CData/*0:0*/ __Vfunc_match__44__Vfuncout;
        CData/*0:0*/ __Vfunc_match__45__Vfuncout;
        CData/*0:0*/ __Vfunc_match__46__Vfuncout;
        CData/*0:0*/ __Vfunc_match__47__Vfuncout;
        CData/*0:0*/ __Vfunc_match__48__Vfuncout;
        CData/*0:0*/ __Vfunc_match__49__Vfuncout;
        CData/*0:0*/ __Vfunc_match__50__Vfuncout;
        CData/*0:0*/ __Vfunc_match__51__Vfuncout;
        CData/*0:0*/ __Vfunc_match__52__Vfuncout;
        CData/*0:0*/ __Vfunc_match__53__Vfuncout;
    };
    struct {
        CData/*0:0*/ __Vfunc_match__54__Vfuncout;
        CData/*0:0*/ __Vfunc_match__55__Vfuncout;
        CData/*6:0*/ __Vtableidx1;
        CData/*5:0*/ __Vtableidx2;
        CData/*4:0*/ __Vdlyvdim0__top__DOT__rv32_gpr_regfile__DOT__rf__v0;
        CData/*3:0*/ __Vdly__top__DOT__u_icache_top__DOT__icache_state;
        CData/*5:0*/ __Vdly__top__DOT__u_icache_top__DOT__blk_addr_reg;
        CData/*6:0*/ __Vdly__top__DOT__u_icache_top__DOT__line_idx_reg;
        CData/*7:0*/ __Vdly__top__DOT__u_icache_top__DOT___ram_rlen_icache_o;
        CData/*3:0*/ __Vdly__top__DOT__u_icache_top__DOT__burst_count;
        CData/*3:0*/ __Vdly__top__DOT__u_dcache_top__DOT__dcache_state;
        CData/*3:0*/ __Vdly__top__DOT__u_dcache_top__DOT__burst_count;
        CData/*0:0*/ __Vdly__top__DOT__u_dcache_top__DOT__dcache_tag_wen;
        CData/*0:0*/ __Vdly__top__DOT__u_dcache_top__DOT__dcache_data_wen;
        CData/*7:0*/ __Vdly__top__DOT__u_dcache_top__DOT___ram_rlen_dcache_o;
        CData/*0:0*/ __Vdly__top__DOT__u_dcache_top__DOT___ram_raddr_valid_dcache_o;
        CData/*0:0*/ __Vdly__top__DOT__u_dcache_top__DOT___ram_waddr_valid_dcache_o;
        CData/*1:0*/ __Vdly__top__DOT__axi_arb__DOT__arb_state;
        CData/*0:0*/ __Vdly__top__DOT__axi4_rw__DOT___arb_wdata_ready_o;
        CData/*0:0*/ __Vdly__top__DOT__axi4_rw__DOT___arb_rlast_o;
        CData/*0:0*/ __Vtrigrprev__TOP__clk;
        CData/*0:0*/ __Vtrigrprev__TOP__rst;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ top__DOT__clint_csr_write_addr;
        SData/*15:0*/ top__DOT__ifu__DOT__bpu__DOT__global_history;
        SData/*9:0*/ top__DOT__ifu__DOT__bpu__DOT__t0_tag_u;
        SData/*9:0*/ top__DOT__ifu__DOT__bpu__DOT__t1_tag_u;
        SData/*8:0*/ top__DOT__ifu__DOT__bpu__DOT__bm_index_u;
        SData/*15:0*/ top__DOT__if2id__DOT___bpu_history_if_id_q;
        SData/*15:0*/ top__DOT__id2ex__DOT___bpu_history_id_ex_q;
        SData/*11:0*/ top__DOT__id2ex__DOT___csr_idx_id_ex_d;
        SData/*11:0*/ top__DOT__id2ex__DOT___csr_idx_id_ex_q;
        SData/*12:0*/ top__DOT__id2ex__DOT___exc_op_id_ex_q;
        SData/*11:0*/ top__DOT__ex2mem__DOT___csr_addr_ex_mem_q;
        VL_OUT(io_master_awaddr,31,0);
        VL_OUT(io_master_wdata,31,0);
        VL_OUT(io_master_araddr,31,0);
        VL_IN(io_master_rdata,31,0);
        IData/*31:0*/ top__DOT__pc_next;
        IData/*31:0*/ top__DOT__bpu_pc_o;
        IData/*31:0*/ top__DOT__pdt_tag;
        IData/*31:0*/ top__DOT__mem_data_mem;
        IData/*31:0*/ top__DOT__mem_wdata;
        IData/*31:0*/ top__DOT__pc_mem_wb;
        IData/*31:0*/ top__DOT__inst_data_mem_wb;
        IData/*31:0*/ top__DOT__mem_data_mem_wb;
        IData/*31:0*/ top__DOT__clint_csr_write_data;
        IData/*31:0*/ top__DOT__ram_rdata_icache;
        IData/*31:0*/ top__DOT__ram_rdata_dcache;
        VlWide<4>/*127:0*/ top__DOT__io_sram0_rdata;
        VlWide<4>/*127:0*/ top__DOT__io_sram1_rdata;
        VlWide<4>/*127:0*/ top__DOT__io_sram2_rdata;
        VlWide<4>/*127:0*/ top__DOT__io_sram3_rdata;
        VlWide<4>/*127:0*/ top__DOT__io_sram4_rdata;
        VlWide<4>/*127:0*/ top__DOT__io_sram5_rdata;
        VlWide<4>/*127:0*/ top__DOT__io_sram6_rdata;
        VlWide<4>/*127:0*/ top__DOT__io_sram7_rdata;
        IData/*31:0*/ top__DOT__u_pc_reg__DOT___pc_current;
        IData/*31:0*/ top__DOT__u_pc_reg__DOT___pc_next_d;
        IData/*19:0*/ top__DOT__ifu__DOT___if_trap_bus;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__total_branches;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__correct_predictions;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__bimodal_hits;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__t0_hits;
    };
    struct {
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__t1_hits;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__btb_hits;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__btb_misses;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__i;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__ras_forward_data;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT__btb_target_val;
        IData/*21:0*/ top__DOT__ifu__DOT__bpu__DOT__btb_tag_u;
        IData/*31:0*/ top__DOT__ifu__DOT__bpu__DOT____VdfgTmp_hb3e3931f__0;
        IData/*31:0*/ top__DOT__if2id__DOT___inst_addr_if_id_q;
        IData/*31:0*/ top__DOT__if2id__DOT___inst_data_if_id_q;
        IData/*31:0*/ top__DOT__if2id__DOT___bpu_pdt_tag_if_id_q;
        IData/*19:0*/ top__DOT__if2id__DOT___trap_bus_if_id_q;
        IData/*19:0*/ top__DOT__idu__DOT___decode_trap_bus;
        IData/*31:0*/ top__DOT__id2ex__DOT___bpu_pdt_tag_id_ex_q;
        IData/*31:0*/ top__DOT__id2ex__DOT___pc_id_ex_q;
        IData/*31:0*/ top__DOT__id2ex__DOT___inst_data_id_ex_q;
        IData/*31:0*/ top__DOT__id2ex__DOT___imm_data_id_ex_q;
        IData/*31:0*/ top__DOT__id2ex__DOT___csr_imm_id_ex_q;
        IData/*31:0*/ top__DOT__id2ex__DOT___csr_data_id_ex_q;
        IData/*31:0*/ top__DOT__id2ex__DOT___rs1_data_id_ex_q;
        IData/*31:0*/ top__DOT__id2ex__DOT___rs2_data_id_ex_q;
        IData/*24:0*/ top__DOT__id2ex__DOT___alu_op_id_ex_q;
        IData/*19:0*/ top__DOT__id2ex__DOT___trap_bus_id_ex_q;
        IData/*31:0*/ top__DOT__exu__DOT__redirect_pc;
        IData/*31:0*/ top__DOT__exu__DOT___alu_in1;
        IData/*31:0*/ top__DOT__exu__DOT___alu_in2;
        IData/*31:0*/ top__DOT__exu__DOT___alu_out;
        IData/*19:0*/ top__DOT__exu__DOT___exc_trap_bus;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT___alu_out;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_shift__DOT___shift_num_inv;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_shift__DOT___shifter_res;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_shift__DOT___srl_res;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__booth_rs1;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__booth_rs2;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div_data;
        IData/*31:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__rem_data;
        VlWide<3>/*65:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__s_reg;
        VlWide<3>/*65:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__s_reg_next32;
        IData/*31:0*/ top__DOT__exu__DOT__u_execute_csr__DOT___csr_op2;
        IData/*31:0*/ top__DOT__ex2mem__DOT___pc_ex_mem_q;
        IData/*31:0*/ top__DOT__ex2mem__DOT___inst_data_ex_mem_q;
        IData/*31:0*/ top__DOT__ex2mem__DOT___rs1_data_ex_mem_q;
        IData/*31:0*/ top__DOT__ex2mem__DOT___rs2_data_ex_mem_q;
        IData/*31:0*/ top__DOT__ex2mem__DOT___imm_data_ex_mem_q;
        IData/*31:0*/ top__DOT__ex2mem__DOT___alu_data_ex_mem_q;
        IData/*31:0*/ top__DOT__ex2mem__DOT___csr_writedata_ex_mem_q;
        IData/*19:0*/ top__DOT__ex2mem__DOT___trap_bus_ex_mem_q;
        IData/*31:0*/ top__DOT__lsu__DOT__rdata_switch;
        IData/*19:0*/ top__DOT__lsu__DOT___mem_trap_bus;
        IData/*31:0*/ top__DOT__clint_u__DOT__cause_value;
        IData/*31:0*/ top__DOT__clint_u__DOT__cause_value_latched;
        IData/*31:0*/ top__DOT__clint_u__DOT__mtime_addr_i;
        IData/*31:0*/ top__DOT__clint_u__DOT__mtime_wdata_i;
        IData/*31:0*/ top__DOT__clint_u__DOT__u_mtime__DOT__mtime_low_q;
        IData/*31:0*/ top__DOT__clint_u__DOT__u_mtime__DOT__mtime_high_q;
        IData/*31:0*/ top__DOT__clint_u__DOT__u_mtime__DOT__mtimecmp_low_q;
        IData/*31:0*/ top__DOT__clint_u__DOT__u_mtime__DOT__mtimecmp_high_q;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__mstatusReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__mtvecReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__mepcReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__mcauseReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__mtvalReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__mieReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__mipReg;
    };
    struct {
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__medelegReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__midelegReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__stvecReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__sepcReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__scauseReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__stvalReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__sstatusReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__sieReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__sipReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__satpReg;
        IData/*31:0*/ top__DOT__rv32_csr_regfile__DOT__read_data;
        IData/*31:0*/ top__DOT__rv32_gpr_regfile__DOT___write_data;
        IData/*31:0*/ top__DOT__u_icache_top__DOT__uncache_rdata;
        IData/*18:0*/ top__DOT__u_icache_top__DOT__line_tag_reg;
        IData/*31:0*/ top__DOT__u_icache_top__DOT___ram_raddr_icache_o;
        IData/*31:0*/ top__DOT__u_icache_top__DOT____Vcellinp__u_uncache_check__addr_check_i;
        IData/*31:0*/ top__DOT__u_icache_top__DOT__icache_final_data;
        IData/*19:0*/ top__DOT__u_icache_top__DOT__u_icache_tag__DOT__read_tag_full;
        IData/*31:0*/ top__DOT__u_icache_top__DOT__u_icache_tag__DOT__i;
        VlWide<4>/*127:0*/ top__DOT__u_icache_top__DOT__u_icache_data__DOT__D;
        IData/*18:0*/ top__DOT__u_dcache_top__DOT__cache_line_tag;
        IData/*31:0*/ top__DOT__u_dcache_top__DOT___ram_raddr_dcache_o;
        IData/*31:0*/ top__DOT__u_dcache_top__DOT___ram_waddr_dcache_o;
        IData/*31:0*/ top__DOT__u_dcache_top__DOT___ram_wdata_dcache_o;
        VlWide<4>/*127:0*/ top__DOT__u_dcache_top__DOT__dcache_wdata_writehit;
        IData/*31:0*/ top__DOT__u_dcache_top__DOT__uncache_rdata;
        VlWide<4>/*127:0*/ top__DOT__u_dcache_top__DOT__dcache_wmask_writehit;
        IData/*19:0*/ top__DOT__u_dcache_top__DOT__u_dcache_tag__DOT__read_tag_full;
        IData/*31:0*/ top__DOT__u_dcache_top__DOT__u_dcache_tag__DOT__i;
        VlWide<4>/*127:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT__D;
        IData/*31:0*/ top__DOT__u_dcache_top__DOT__u_dcache_data__DOT__dcache_wb_data;
        IData/*31:0*/ top__DOT__axi_arb__DOT___arb_read_addr_o;
        IData/*31:0*/ top__DOT__axi4_rw__DOT__aw_addr;
        IData/*31:0*/ top__DOT__axi4_rw__DOT___arb_rdata_o;
        IData/*31:0*/ top__DOT__axi4_rw__DOT__ar_addr;
        VlWide<4>/*127:0*/ top__DOT__sram__DOT__SRAM0__DOT__bwen;
        VlWide<4>/*127:0*/ top__DOT__sram__DOT__SRAM4__DOT__bwen;
        IData/*31:0*/ __Vfunc_match__2__inst;
        IData/*31:0*/ __Vfunc_match__3__inst;
        IData/*31:0*/ __Vfunc_match__4__inst;
        IData/*31:0*/ __Vfunc_match__5__inst;
        IData/*31:0*/ __Vfunc_match__6__inst;
        IData/*31:0*/ __Vfunc_match__7__inst;
        IData/*31:0*/ __Vfunc_match__8__inst;
        IData/*31:0*/ __Vfunc_match__9__inst;
        IData/*31:0*/ __Vfunc_match__10__inst;
        IData/*31:0*/ __Vfunc_match__11__inst;
        IData/*31:0*/ __Vfunc_match__12__inst;
        IData/*31:0*/ __Vfunc_match__13__inst;
        IData/*31:0*/ __Vfunc_match__14__inst;
        IData/*31:0*/ __Vfunc_match__15__inst;
        IData/*31:0*/ __Vfunc_match__16__inst;
        IData/*31:0*/ __Vfunc_match__17__inst;
        IData/*31:0*/ __Vfunc_match__18__inst;
        IData/*31:0*/ __Vfunc_match__19__inst;
        IData/*31:0*/ __Vfunc_match__20__inst;
        IData/*31:0*/ __Vfunc_match__21__inst;
        IData/*31:0*/ __Vfunc_match__22__inst;
        IData/*31:0*/ __Vfunc_match__23__inst;
        IData/*31:0*/ __Vfunc_match__24__inst;
        IData/*31:0*/ __Vfunc_match__25__inst;
        IData/*31:0*/ __Vfunc_match__26__inst;
        IData/*31:0*/ __Vfunc_match__27__inst;
        IData/*31:0*/ __Vfunc_match__28__inst;
    };
    struct {
        IData/*31:0*/ __Vfunc_match__29__inst;
        IData/*31:0*/ __Vfunc_match__30__inst;
        IData/*31:0*/ __Vfunc_match__31__inst;
        IData/*31:0*/ __Vfunc_match__32__inst;
        IData/*31:0*/ __Vfunc_match__33__inst;
        IData/*31:0*/ __Vfunc_match__34__inst;
        IData/*31:0*/ __Vfunc_match__35__inst;
        IData/*31:0*/ __Vfunc_match__36__inst;
        IData/*31:0*/ __Vfunc_match__37__inst;
        IData/*31:0*/ __Vfunc_match__38__inst;
        IData/*31:0*/ __Vfunc_match__39__inst;
        IData/*31:0*/ __Vfunc_match__40__inst;
        IData/*31:0*/ __Vfunc_match__41__inst;
        IData/*31:0*/ __Vfunc_match__42__inst;
        IData/*31:0*/ __Vfunc_match__43__inst;
        IData/*31:0*/ __Vfunc_match__44__inst;
        IData/*31:0*/ __Vfunc_match__45__inst;
        IData/*31:0*/ __Vfunc_match__46__inst;
        IData/*31:0*/ __Vfunc_match__47__inst;
        IData/*31:0*/ __Vfunc_match__48__inst;
        IData/*31:0*/ __Vfunc_match__49__inst;
        IData/*31:0*/ __Vfunc_match__50__inst;
        IData/*31:0*/ __Vfunc_match__51__inst;
        IData/*31:0*/ __Vfunc_match__52__inst;
        IData/*31:0*/ __Vfunc_match__53__inst;
        IData/*31:0*/ __Vfunc_match__54__inst;
        IData/*31:0*/ __Vfunc_match__55__inst;
        IData/*31:0*/ __Vdlyvval__top__DOT__rv32_gpr_regfile__DOT__rf__v0;
        IData/*18:0*/ __Vdly__top__DOT__u_icache_top__DOT__line_tag_reg;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT___alu_b;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT___add_out;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__mul_data64;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__mul_final_a;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__mul_final_b;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__0__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__1__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__2__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__3__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__4__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__5__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__6__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__7__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__8__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__9__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__10__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__11__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__12__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__13__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__14__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__15__KET____DOT__u_regTemplate__dout;
        QData/*63:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT____Vcellout__genblk1__BRA__16__KET____DOT__u_regTemplate__dout;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__rs1_34;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__rs2_34;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_hf6214425__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_hc6528860__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_h9ed15e07__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_h6568449b__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_h8d75619e__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_h518c77c4__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_hc9138a91__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_hfa98297c__0;
    };
    struct {
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_heedd88a8__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_hd66b1d0c__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_h690ba010__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_h0aa273b8__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_ha506d195__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_hf184b46c__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_ha67af118__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_hdbbb5045__0;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT____VdfgTmp_ha448e796__0;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__d_reg;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__d_neg_reg;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div_count;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div32_divisor;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__d_switch_32;
        QData/*33:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__q_correct_32;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__s_correct_32;
        QData/*32:0*/ top__DOT__exu__DOT__u_alu__DOT__u_alu_div_top__DOT__u_alu_div_slow_32__DOT__div_count_next;
        VlUnpacked<CData/*1:0*/, 512> top__DOT__ifu__DOT__bpu__DOT__bimodal_table;
        VlUnpacked<SData/*9:0*/, 256> top__DOT__ifu__DOT__bpu__DOT__t0_tag;
        VlUnpacked<CData/*1:0*/, 256> top__DOT__ifu__DOT__bpu__DOT__t0_counter;
        VlUnpacked<SData/*9:0*/, 256> top__DOT__ifu__DOT__bpu__DOT__t1_tag;
        VlUnpacked<CData/*1:0*/, 256> top__DOT__ifu__DOT__bpu__DOT__t1_counter;
        VlUnpacked<IData/*21:0*/, 256> top__DOT__ifu__DOT__bpu__DOT__btb_tag;
        VlUnpacked<IData/*31:0*/, 256> top__DOT__ifu__DOT__bpu__DOT__btb_target;
        VlUnpacked<CData/*0:0*/, 256> top__DOT__ifu__DOT__bpu__DOT__btb_valid;
        VlUnpacked<IData/*31:0*/, 64> top__DOT__ifu__DOT__bpu__DOT__ras;
        VlUnpacked<QData/*63:0*/, 17> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__Partial_product;
        VlUnpacked<QData/*63:0*/, 17> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step1_pp_q;
        VlUnpacked<QData/*63:0*/, 5> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step1_sum;
        VlUnpacked<QData/*63:0*/, 5> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step1_carry;
        VlUnpacked<QData/*63:0*/, 12> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step2_pp_q;
        VlUnpacked<QData/*63:0*/, 4> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step2_sum;
        VlUnpacked<QData/*63:0*/, 4> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step2_carry;
        VlUnpacked<QData/*63:0*/, 8> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step3_pp_q;
        VlUnpacked<QData/*63:0*/, 2> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step3_sum;
        VlUnpacked<QData/*63:0*/, 2> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step3_carry;
        VlUnpacked<QData/*63:0*/, 6> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step4_pp_q;
        VlUnpacked<QData/*63:0*/, 2> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step4_sum;
        VlUnpacked<QData/*63:0*/, 2> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step4_carry;
        VlUnpacked<QData/*63:0*/, 4> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step5_pp_q;
        VlUnpacked<QData/*63:0*/, 1> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step5_sum;
        VlUnpacked<QData/*63:0*/, 1> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step5_carry;
        VlUnpacked<QData/*63:0*/, 3> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step6_pp_q;
        VlUnpacked<QData/*63:0*/, 1> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step6_sum;
        VlUnpacked<QData/*63:0*/, 1> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__step6_carry;
        VlUnpacked<QData/*33:0*/, 17> top__DOT__exu__DOT__u_alu__DOT__u_alu_mul_top__DOT__u_alu_mul_wallace__DOT__u_alu_mul_booth_r4_32__DOT__pp_o;
        VlUnpacked<IData/*31:0*/, 18> top__DOT__rv32_csr_regfile__DOT__csr_regs;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__rv32_gpr_regfile__DOT__rf;
        VlUnpacked<IData/*19:0*/, 128> top__DOT__u_icache_top__DOT__u_icache_tag__DOT__icache_tag_regs;
        VlUnpacked<IData/*19:0*/, 128> top__DOT__u_dcache_top__DOT__u_dcache_tag__DOT__dcache_tag_regs;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM0__DOT__ram;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM1__DOT__ram;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM2__DOT__ram;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM3__DOT__ram;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM4__DOT__ram;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM5__DOT__ram;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM6__DOT__ram;
        VlUnpacked<VlWide<4>/*127:0*/, 128> top__DOT__sram__DOT__SRAM7__DOT__ram;
        VlUnpacked<CData/*0:0*/, 6> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
